Cypress.Commands.add('fillForm', () => {
	cy.get('#id_gender1').check()
	cy.get('#customer_firstname').type('Bernardo')
	cy.get('#customer_lastname').type('Teste')
	cy.get('#passwd').type('12345678901', { log: false })
	cy.get('#days').select(20)
	cy.get('#months').select(12)
	cy.get('#years').select('1984')
	cy.get('#newsletter').check()
	cy.get('#optin').check()
	cy.get('#address1').type('820 Beloit Ave')
	cy.get('#city').type('Chicago')
	cy.get('#id_state').select('Illinois')
	cy.get('#postcode').type('60130')
	cy.get('#phone_mobile').type('+1 555-666-888')
	cy.get('#alias').clear().type('Hooome')
	//cy.get('#submitAccount > span').click()
})
